### ISSUE TITLE
Does not work as expected when using a gltf "part" that has more than one material

### ISSUE THREAD

**Issue by kfarr** [kfarr/aframe-gltf-helpers#2]
via @diarmidmackenzie

> Are you sure that gltf-part-plus supports multiple meshes within a GLTF model?  Have had a quick look at the source code here, and it's not obvious to me that it does.
> https://github.com/kfarr/aframe-gltf-helpers/blob/master/index.js
> 
> If I remove the instancing completely, and just try to show an individual model, it seems like I just see the glass.
> https://multi-mesh-instancing.glitch.me/

For further research:
- Create test cases for - does gltf part plus work with gltf that have multiple materials?

**Comment by donmccurdy** [comment]
Looking at this snippet:

https://github.com/kfarr/aframe-gltf-helpers/blob/8fff88dfe3f876d4092d30a382870eef0c21eb31/index.js#L106-L112

The effect here is to find the first Mesh within the referenced part, and just return that. GLTFLoader doesn't ever create meshes with multiple materials, but it does return nested groups sometimes, as is the case here. In the Glitch demo the referenced part is `building_5`, which has several meshes within it:

<img width="668" alt="Screen Shot 2021-09-28 at 5 20 50 PM" src="https://user-images.githubusercontent.com/1848368/135182830-5bc3555e-8a7c-4088-8070-dad508a7aa5c.png">

Unless there's some other reason that gltf-part-plus _needs_ to return only a single mesh, it might be better to return the whole subtree.

**Comment by kfarr** [comment]
Thanks @donmccurdy yes removing those lines resolved the issue! Closed with https://github.com/kfarr/aframe-gltf-helpers/commit/8d622be71672451f5ef20237d9dd1ee09f8d2b42
